services:
    gorgo_entity_config_debug.command.list_configurable_fields:
        class: 'Gorgo\Bundle\EntityConfigDebugBundle\Command\ListConfigurableFieldsCommand'
        arguments:
            - '@doctrine'
            - '@oro_entity_config.config_manager'
        tags:
            - { name: console.command }
